In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt

In [2]:
all_files=[]
import os
for root, dirs, files in os.walk("./"):
    for file in files:
        if file.endswith(".csv"):
             all_files.append(os.path.join(root, file))

In [3]:
dfs=[]
for path in all_files:
    df = pd.read_csv(path,index_col='datetime',sep=';',parse_dates=True)
    dfs.append(df)
print('Features:')
for col in dfs[2].columns:
    print('\t',col)

Features:
	 Accelerometer1RMS
	 Accelerometer2RMS
	 Current
	 Pressure
	 Temperature
	 Thermocouple
	 Voltage
	 Volume Flow RateRMS
	 anomaly
	 changepoint

If we need to load a specific type of experiments:

In [4]:
i,sum_an,sum_cp = 0,0,0
for df in dfs[1:]:
    sum_an += df.anomaly.sum()
    sum_cp += df.changepoint.sum()
    i +=1

In [5]:
i,sum_an,sum_cp

(34, 13241.0, 130.0)

In [4]:
# dfs=[]
# for path in all_files:
#     if 'valve2' in path:
#         df = pd.read_csv(path,index_col='datetime',sep=';',parse_dates=True)
#         dfs.append(df)
#         print(len(df),df.index[-1]-df.index[0])
#         plt.plot(df['Volume Flow RateRMS'][500:].rolling(5).mean().values,label=path)
# plt.legend()

**dfs** is the list of pandas.dataframes with experiments

# Statistical properties

In [5]:
from IPython.display import display

In [47]:
for i in range(len(dfs)):
    print(all_files[i].replace("/","\\"))
    display(dfs[i].describe())

.\anomaly-free\anomaly-free.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS
count,9401.000000,9401.000000,9401.000000,9401.000000,9401.000000,9401.000000,9401.000000,9401.000000
mean,0.212277,0.268553,2.568057,0.111429,89.506955,28.417508,228.490887,125.140908
std,0.004728,0.004129,6.082034,0.252583,0.673482,0.757808,12.579837,1.671961
min,0.193992,0.248062,0.855284,-1.257000,88.171300,26.765800,1.036640,118.000000
25%,0.210431,0.265524,2.129540,0.054711,88.974200,27.841900,222.625000,124.000000
50%,0.212928,0.267378,2.541080,0.054711,89.380500,28.624800,228.942000,125.672000
75%,0.215262,0.271934,2.728380,0.382638,89.922400,29.068500,234.963000,126.328000
max,0.225967,0.280214,233.203000,1.366420,91.724900,29.522100,252.806000,128.353000

.\other\11.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,665.000000,665.000000,665.000000,665.000000,665.000000,665.000000,665.000000,665.000000,665.000000,665.000000
mean,0.079733,0.130707,1.926646,0.002440,87.953613,22.101079,230.308699,74.541546,0.577444,0.006015
std,0.007020,0.011649,8.932977,0.263618,0.670718,0.018344,13.904155,6.631012,0.494338,0.077381
min,0.000000,0.000000,0.589853,-1.257000,86.553400,22.067000,1.979620,0.000000,0.000000,0.000000
25%,0.079977,0.129748,1.220290,-0.273216,87.370500,22.086000,224.340000,74.000000,0.000000,0.000000
50%,0.080419,0.131496,1.687290,0.054711,88.091800,22.100500,230.871000,75.000000,1.000000,0.000000
75%,0.080931,0.133519,1.887060,0.054711,88.457500,22.116100,237.324000,76.019400,1.000000,0.000000
max,0.082504,0.138089,231.720000,0.710565,89.151000,22.143200,254.128000,77.980600,1.000000,1.000000

.\other\12.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1137.000000,1137.000000,1137.000000,1137.000000,1137.000000,1137.000000,1137.000000,1137.000000,1137.000000,1137.000000
mean,0.081098,0.132212,1.573211,0.011449,86.980258,22.112552,230.035659,76.047435,0.350044,0.003518
std,0.000639,0.002566,0.385167,0.256350,0.857701,0.016770,11.052438,1.041825,0.477193,0.059235
min,0.079158,0.125210,0.598223,-0.601143,85.280200,22.078000,203.887000,74.000000,0.000000,0.000000
25%,0.080629,0.130171,1.296880,-0.273216,86.364100,22.099900,223.636000,75.000000,0.000000,0.000000
50%,0.081074,0.132053,1.654900,0.054711,86.824800,22.110100,230.496000,76.020100,0.000000,0.000000
75%,0.081548,0.134189,1.869030,0.054711,87.596400,22.126100,236.537000,77.000000,1.000000,0.000000
max,0.083113,0.138839,2.328460,0.710565,88.993500,22.155600,254.611000,78.000000,1.000000,1.000000

.\other\13.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000
mean,0.081078,0.132600,1.568593,0.013720,86.941553,22.091347,229.702999,74.424737,0.411157,0.004132
std,0.005878,0.009938,0.381874,0.271711,0.597618,0.020845,10.915416,5.867244,0.492298,0.064183
min,0.000000,0.000000,0.601484,-0.601143,85.538700,22.020900,203.884000,0.000000,0.000000,0.000000
25%,0.081035,0.131134,1.267692,-0.273216,86.463350,22.080500,223.559250,72.000000,0.000000,0.000000
50%,0.081507,0.133049,1.641210,0.054711,87.010400,22.094700,230.203500,75.021100,0.000000,0.000000
75%,0.081942,0.135319,1.865890,0.054711,87.421525,22.104950,236.128000,77.000000,1.000000,0.000000
max,0.083262,0.141581,2.347860,0.710565,88.133000,22.133900,254.065000,78.000000,1.000000,1.000000

.\other\14.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1153.000000,1153.000000,1153.000000,1153.000000,1153.000000,1153.000000,1153.000000,1153.000000,1153.000000,1153.000000
mean,0.349906,0.419001,2.624921,0.109603,88.727598,29.361947,228.551417,126.152414,0.355594,0.001735
std,0.193911,0.218177,6.684815,0.267872,0.287631,0.022597,12.900195,0.486211,0.478901,0.041631
min,0.188217,0.249319,0.889359,-0.601143,87.939300,29.311000,2.639530,124.323000,0.000000,0.000000
25%,0.216147,0.268403,2.177520,0.054711,88.480100,29.346800,223.104000,126.000000,0.000000,0.000000
50%,0.219158,0.271992,2.565070,0.054711,88.733900,29.356100,228.913000,126.000000,0.000000,0.000000
75%,0.625555,0.719428,2.742790,0.382638,88.959000,29.372800,235.242000,126.647000,1.000000,0.000000
max,0.722747,0.800498,228.839000,1.038490,89.380800,29.458300,252.473000,127.679000,1.000000,1.000000

.\other\15.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1147.000000,1147.000000,1147.000000,1147.000000,1147.000000,1147.000000,1147.000000,1147.000000,1147.000000,1147.000000
mean,0.343183,0.396699,2.436760,0.113892,88.653720,29.568254,228.782357,126.733533,0.349608,0.003487
std,0.191054,0.196558,0.456951,0.256592,0.317396,0.052532,10.412964,0.673467,0.477054,0.058977
min,0.191008,0.248731,0.887818,-0.929070,87.890000,29.424400,202.335000,124.644000,0.000000,0.000000
25%,0.210402,0.261537,2.177170,0.054711,88.437100,29.540300,223.413500,126.321000,0.000000,0.000000
50%,0.212671,0.263915,2.553140,0.054711,88.630700,29.574300,228.860000,127.000000,0.000000,0.000000
75%,0.630258,0.691622,2.744340,0.382638,88.912200,29.610200,234.189500,127.000000,1.000000,0.000000
max,0.658716,0.735456,3.207430,1.038490,89.384400,29.658900,252.171000,128.680000,1.000000,1.000000

.\other\16.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1091.000000,1091.000000,1091.000000,1091.000000,1091.000000,1091.000000,1091.000000,1091.000000,1091.000000,1091.000000
mean,0.315882,0.367016,2.382214,0.117231,88.503252,29.764996,227.815712,127.008371,0.317140,0.003666
std,0.164745,0.175649,0.484264,0.260974,0.321574,0.079044,10.855712,0.859505,0.465576,0.060467
min,0.188173,0.229814,0.901802,-0.601143,87.665600,29.611300,201.555000,124.000000,0.000000,0.000000
25%,0.213440,0.258815,2.110615,0.054711,88.278800,29.715550,221.483000,126.321000,0.000000,0.000000
50%,0.216232,0.261736,2.503460,0.054711,88.466400,29.761300,228.498000,127.000000,0.000000,0.000000
75%,0.407837,0.461080,2.710155,0.382638,88.773400,29.803500,233.937500,127.682000,1.000000,0.000000
max,0.649273,0.732399,3.223400,1.038490,89.279300,30.024200,252.107000,129.365000,1.000000,1.000000

.\other\17.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1147.000000,1147.000000,1147.000000,1147.000000,1147.00000,1147.000000,1147.000000,1147.000000,1147.000000,1147.000000
mean,0.219722,0.264393,2.794136,0.127330,88.35152,29.860100,227.654492,127.566976,0.351351,0.003487
std,0.011639,0.012393,9.390838,0.259882,0.28483,0.046355,14.523556,0.629600,0.477601,0.058977
min,0.208880,0.256805,0.897348,-0.601143,87.70880,29.776000,2.059780,125.317000,0.000000,0.000000
25%,0.216657,0.262125,2.117420,0.054711,88.09830,29.826300,221.836000,127.000000,0.000000,0.000000
50%,0.219330,0.264037,2.552510,0.054711,88.37050,29.845500,228.337000,127.683000,0.000000,0.000000
75%,0.222093,0.265859,2.738025,0.382638,88.58855,29.890350,234.497500,128.000000,1.000000,0.000000
max,0.589896,0.673331,237.111000,1.038490,89.00980,29.998900,252.023000,129.684000,1.000000,1.000000

.\other\18.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1145.000000,1145.000000,1145.000000,1145.000000,1145.000000,1145.00000,1145.000000,1145.000000,1145.000000,1145.000000
mean,0.345927,0.396581,2.421803,0.114855,87.445034,29.68201,227.797613,127.086658,0.351092,0.003493
std,0.180635,0.194111,0.498078,0.244024,0.658721,0.20667,11.438814,1.268125,0.477520,0.059028
min,0.210494,0.253698,0.884918,-0.601143,86.025800,29.32210,200.744000,123.316000,0.000000,0.000000
25%,0.228336,0.270778,2.123800,0.054711,86.927800,29.51250,221.849000,126.317000,0.000000,0.000000
50%,0.233113,0.275407,2.558130,0.054711,87.480600,29.69200,227.894000,127.634000,0.000000,0.000000
75%,0.627058,0.696501,2.763650,0.382638,87.956400,29.82110,234.451000,128.000000,1.000000,0.000000
max,0.657403,0.750723,3.259970,0.710565,88.844600,30.11020,251.612000,129.000000,1.000000,1.000000

.\other\19.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000
mean,0.235381,0.282291,2.647146,0.097248,86.095052,30.115282,226.675179,127.893526,0.442685,0.003017
std,0.022195,0.022814,6.512015,0.254440,0.419548,1.243577,12.351044,1.970199,0.496892,0.054861
min,0.209199,0.250680,0.914024,-0.929070,85.031900,28.819100,2.611080,124.632000,0.000000,0.000000
25%,0.229211,0.277066,2.197913,0.054711,85.788225,29.186150,220.682000,126.315000,0.000000,0.000000
50%,0.232891,0.279963,2.587325,0.054711,86.105700,29.285600,227.212000,127.000000,0.000000,0.000000
75%,0.236586,0.283660,2.778335,0.382638,86.383475,31.679275,232.833500,129.688000,1.000000,0.000000
max,0.498573,0.556955,239.003000,1.038490,87.029300,32.077300,250.821000,133.688000,1.000000,1.000000

.\other\20.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1191.000000,1191.000000,1191.000000,1191.000000,1191.000000,1191.000000,1191.000000,1191.000000,1191.000000,1191.000000
mean,0.238646,0.290395,2.418080,0.098214,85.137640,30.768303,227.525908,128.262455,0.378673,0.003359
std,0.004933,0.008191,0.495027,0.264646,0.357162,0.527378,10.930676,0.779631,0.485260,0.057880
min,0.226751,0.273341,0.933653,-1.257000,84.401000,29.960000,201.265000,125.312000,0.000000,0.000000
25%,0.235512,0.283859,2.133500,0.054711,84.850450,30.224800,221.739500,128.000000,0.000000,0.000000
50%,0.238227,0.288316,2.553740,0.054711,85.131600,30.744700,227.806000,128.312000,0.000000,0.000000
75%,0.241025,0.298242,2.756350,0.382638,85.360800,31.277700,234.011500,128.690000,1.000000,0.000000
max,0.257534,0.309150,3.296250,1.038490,86.006300,31.628800,251.138000,130.690000,1.000000,1.000000

.\other\21.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000
mean,0.247787,0.293245,3.040652,0.101270,85.045519,29.497270,227.551077,98.653472,0.351446,0.003506
std,0.008618,0.005778,11.768187,0.240074,0.397578,0.179618,17.288907,48.556641,0.477631,0.059131
min,0.231597,0.280200,0.846923,-0.601143,84.200400,29.205600,2.166410,0.000000,0.000000,0.000000
25%,0.240961,0.288979,2.155140,0.054711,84.758700,29.351200,222.314000,71.677200,0.000000,0.000000
50%,0.246026,0.292864,2.572020,0.054711,85.029500,29.481800,228.322000,125.691000,0.000000,0.000000
75%,0.253381,0.296958,2.765280,0.382638,85.322300,29.635100,234.133000,127.000000,1.000000,0.000000
max,0.269281,0.314295,234.844000,0.710565,86.171500,29.986600,251.492000,128.383000,1.000000,1.000000

.\other\22.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1079.000000,1079.000000,1079.000000,1079.000000,1079.000000,1079.000000,1079.00000,1079.000000,1079.000000,1079.000000
mean,0.250099,0.292681,2.837208,0.095740,85.523095,29.118154,227.86706,85.897935,0.314180,0.003707
std,0.008596,0.007124,9.827542,0.252694,0.325447,0.186352,14.82652,53.413428,0.464404,0.060801
min,0.236533,0.278392,0.846923,-0.601143,84.741900,28.848500,2.16641,0.000000,0.000000,0.000000
25%,0.243456,0.287127,2.137445,0.054711,85.265550,28.966950,222.31850,26.600000,0.000000,0.000000
50%,0.246230,0.291659,2.568820,0.054711,85.514000,29.079900,228.21700,124.000000,0.000000,0.000000
75%,0.259474,0.297578,2.754360,0.382638,85.785350,29.285750,234.54950,125.309000,1.000000,0.000000
max,0.270455,0.314883,233.630000,1.366420,86.244400,29.454200,251.34400,127.692000,1.000000,1.000000

.\other\23.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000
mean,0.247678,0.290966,2.412848,0.111250,86.163119,29.756159,227.442655,127.105187,0.288314,0.002874
std,0.003084,0.005351,0.503593,0.258271,0.302425,1.860624,10.421399,1.575563,0.453195,0.053554
min,0.234250,0.278720,0.905406,-0.929070,85.458900,28.688600,201.967000,124.000000,0.000000,0.000000
25%,0.245842,0.286859,2.113423,0.054711,85.914050,28.740650,221.999250,126.000000,0.000000,0.000000
50%,0.247756,0.290905,2.566680,0.054711,86.136050,28.758100,227.706500,126.693000,0.000000,0.000000
75%,0.249734,0.294650,2.762258,0.382638,86.409700,28.794100,233.548500,127.694000,1.000000,0.000000
max,0.256944,0.306503,3.309790,0.710565,86.915500,33.415100,251.540000,131.390000,1.000000,1.000000

.\other\9.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000
mean,0.079906,0.130042,1.568759,0.059951,92.553678,22.237701,230.303735,75.549011,0.258322,0.002663
std,0.007269,0.012062,0.386157,0.275617,1.931835,0.018502,11.027365,6.881327,0.438004,0.051571
min,0.000000,0.000000,0.589101,-0.929070,88.811900,22.193700,203.973000,0.000000,0.000000,0.000000
25%,0.079668,0.128999,1.304300,0.054711,90.407300,22.224400,224.042500,76.000000,0.000000,0.000000
50%,0.080307,0.130923,1.637560,0.054711,93.268100,22.237700,230.991000,76.961000,0.000000,0.000000
75%,0.081347,0.133093,1.859575,0.054711,94.196900,22.251500,237.224500,77.000000,1.000000,0.000000
max,0.083569,0.139038,2.328130,0.710565,95.011400,22.281900,254.511000,77.980600,1.000000,1.000000

.\valve1\0.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000
mean,0.026521,0.040173,1.409799,0.084133,77.437466,25.958166,230.322345,32.021791,0.349303,0.003484
std,0.000329,0.000773,9.712153,0.249460,1.745231,0.078422,15.910242,0.458517,0.476958,0.058951
min,0.025553,0.038072,0.388229,-0.601143,74.237000,25.829900,1.087350,31.000000,0.000000,0.000000
25%,0.026293,0.039631,0.794239,0.054711,75.663450,25.878800,225.265500,32.000000,0.000000,0.000000
50%,0.026521,0.040172,1.035150,0.054711,78.384500,25.954700,231.315500,32.000000,0.000000,0.000000
75%,0.026742,0.040697,1.222870,0.382638,78.917275,26.020100,237.097250,32.000000,1.000000,0.000000
max,0.027489,0.043046,235.511000,0.710565,79.889100,26.104400,255.324000,32.998600,1.000000,1.000000

.\valve1\1.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1145.000000,1145.000000,1145.000000,1145.000000,1145.000000,1145.000000,1145.000000,1145.000000,1145.000000,1145.000000
mean,0.026868,0.040045,1.375946,0.074473,73.713523,25.740027,231.016539,31.566819,0.351092,0.003493
std,0.000313,0.000988,9.505229,0.249990,1.333144,0.063399,14.434914,0.760021,0.477520,0.059028
min,0.025834,0.037609,0.375488,-0.929070,71.000400,25.611100,0.636576,30.000000,0.000000,0.000000
25%,0.026648,0.039406,0.736437,0.054711,72.789200,25.690000,225.764000,31.000000,0.000000,0.000000
50%,0.026869,0.039965,0.997305,0.054711,73.908600,25.745900,231.289000,32.000000,0.000000,0.000000
75%,0.027078,0.040583,1.208870,0.054711,74.270600,25.781900,237.540000,32.000000,1.000000,0.000000
max,0.027946,0.053439,237.466000,1.038490,76.280100,25.924000,254.520000,33.000000,1.000000,1.000000

.\valve1\10.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1146.000000,1146.000000,1146.000000,1146.000000,1146.000000,1146.000000,1146.000000,1146.000000,1146.000000,1146.000000
mean,0.027755,0.041471,0.970104,0.063295,68.517408,24.751428,230.386684,31.523800,0.349913,0.003490
std,0.000481,0.001685,0.277052,0.264199,0.892976,0.016573,11.421049,1.157294,0.477150,0.059002
min,0.026094,0.038207,0.399169,-0.601143,66.236000,24.718100,203.518000,29.000000,0.000000,0.000000
25%,0.027391,0.040347,0.731540,0.054711,67.866225,24.740800,223.675250,30.000000,0.000000,0.000000
50%,0.027762,0.041251,0.985958,0.054711,68.570450,24.749800,230.646000,32.000000,0.000000,0.000000
75%,0.028126,0.042215,1.193158,0.054711,69.239675,24.758400,237.005000,32.020100,1.000000,0.000000
max,0.028911,0.047824,1.569300,1.038490,70.156000,24.833300,254.767000,32.980800,1.000000,1.000000

.\valve1\11.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000,1141.000000
mean,0.027751,0.040907,0.969842,0.059597,68.647531,24.705572,230.723006,30.941518,0.349693,0.003506
std,0.000399,0.001347,0.275486,0.255999,0.732862,0.023997,10.857888,2.215194,0.477082,0.059131
min,0.026624,0.037776,0.385309,-0.601143,66.626100,24.641400,203.382000,26.977200,0.000000,0.000000
25%,0.027474,0.040038,0.733006,0.054711,68.220100,24.689200,224.297000,28.000000,0.000000,0.000000
50%,0.027760,0.040696,0.966102,0.054711,68.863400,24.707000,231.108000,32.000000,0.000000,0.000000
75%,0.028007,0.041446,1.207940,0.054711,69.205600,24.723100,236.827000,32.023100,1.000000,0.000000
max,0.029031,0.046650,1.539030,0.710565,69.797700,24.756900,254.663000,33.000000,1.000000,1.000000

.\valve1\12.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000
mean,0.027476,0.040633,0.972674,0.058738,68.610787,24.654054,230.242763,30.981714,0.350000,0.003509
std,0.000367,0.001390,0.274368,0.254091,1.274362,0.021407,10.653245,1.665692,0.477179,0.059157
min,0.026445,0.037547,0.372564,-0.929070,65.420200,24.580700,204.222000,28.000000,0.000000,0.000000
25%,0.027219,0.039697,0.737613,0.054711,67.830225,24.644000,224.507750,29.000000,0.000000,0.000000
50%,0.027508,0.040424,0.978509,0.054711,68.722500,24.653600,230.836000,32.000000,0.000000,0.000000
75%,0.027737,0.041349,1.206535,0.054711,69.774275,24.664600,236.145250,32.000000,1.000000,0.000000
max,0.028437,0.047115,1.560930,0.710565,70.485700,24.726400,254.613000,33.000000,1.000000,1.000000

.\valve1\13.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000
mean,0.027546,0.040642,0.968501,0.047520,67.613386,24.580039,230.821466,30.028251,0.350000,0.003509
std,0.000373,0.000986,0.269974,0.259354,0.869162,0.017420,10.614452,3.770802,0.477179,0.059157
min,0.026283,0.037739,0.397457,-0.929070,65.392500,24.532400,204.082000,23.000000,0.000000,0.000000
25%,0.027301,0.039940,0.735012,0.054711,67.055000,24.570300,224.908500,24.947000,0.000000,0.000000
50%,0.027560,0.040658,0.979753,0.054711,67.877150,24.581350,231.090500,32.000000,0.000000,0.000000
75%,0.027818,0.041327,1.197797,0.054711,68.219875,24.590100,237.050250,32.971900,1.000000,0.000000
max,0.028727,0.043859,1.566110,0.710565,69.052100,24.630300,255.112000,33.000000,1.000000,1.000000

.\valve1\14.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1139.000000,1139.000000,1139.000000,1139.000000,1139.000000,1139.000000,1139.000000,1139.000000,1139.000000,1139.000000
mean,0.027453,0.040206,0.961433,0.045210,67.957457,24.518635,230.529262,31.244983,0.350307,0.003512
std,0.000363,0.000922,0.272261,0.257932,0.766250,0.022812,10.744575,1.842267,0.477276,0.059183
min,0.026196,0.037340,0.409186,-0.601143,66.016600,24.468300,203.682000,27.030300,0.000000,0.000000
25%,0.027206,0.039573,0.727414,0.054711,67.557150,24.503450,224.636500,28.985350,0.000000,0.000000
50%,0.027467,0.040226,0.964580,0.054711,68.134400,24.516600,231.004000,32.000000,0.000000,0.000000
75%,0.027717,0.040853,1.187245,0.054711,68.569950,24.529700,236.743000,32.956750,1.000000,0.000000
max,0.028416,0.042578,1.554750,1.038490,69.098400,24.594400,254.261000,33.000000,1.000000,1.000000

.\valve1\15.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000,1150.000000
mean,0.027489,0.040367,0.965749,0.026766,67.871012,24.477360,230.773797,30.042898,0.351304,0.003478
std,0.000372,0.000999,0.265952,0.261679,1.099208,0.032416,10.939755,4.344509,0.477586,0.058900
min,0.026406,0.037339,0.389240,-1.257000,65.188700,24.418700,203.615000,22.000000,0.000000,0.000000
25%,0.027243,0.039707,0.757077,-0.273216,67.026900,24.456400,225.094250,23.051125,0.000000,0.000000
50%,0.027491,0.040405,0.976063,0.054711,68.184400,24.467850,230.940000,32.032700,0.000000,0.000000
75%,0.027748,0.041088,1.187855,0.054711,68.695275,24.500625,237.181750,32.969400,1.000000,0.000000
max,0.028698,0.042862,1.514200,0.710565,69.624800,24.586000,254.701000,33.969400,1.000000,1.000000

.\valve1\2.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1075.000000,1075.000000,1075.000000,1075.000000,1075.000000,1075.00000,1075.000000,1075.000000,1075.000000,1075.000000
mean,0.026884,0.040252,0.973053,0.086436,71.672276,25.55476,230.923116,31.703273,0.313488,0.002791
std,0.000350,0.000928,0.276491,0.249946,1.024446,0.06864,10.423567,0.573500,0.464127,0.052778
min,0.025584,0.037474,0.410492,-0.601143,69.243100,25.45720,203.725000,30.001000,0.000000,0.000000
25%,0.026655,0.039610,0.729415,0.054711,71.046550,25.48980,225.132000,31.001700,0.000000,0.000000
50%,0.026888,0.040297,0.999684,0.054711,71.618600,25.54020,231.144000,32.000000,0.000000,0.000000
75%,0.027131,0.040918,1.203045,0.218674,72.649800,25.60535,236.417500,32.000000,1.000000,0.000000
max,0.027862,0.042919,1.598950,0.710565,73.421800,25.76210,254.957000,32.998800,1.000000,1.000000

.\valve1\3.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1149.000000,1149.000000,1149.000000,1149.000000,1149.000000,1149.000000,1149.000000,1149.000000,1149.000000,1149.000000
mean,0.026957,0.040097,1.340238,0.060704,70.950950,25.496252,230.404491,31.576199,0.351610,0.003481
std,0.000378,0.000828,8.554650,0.262680,0.546608,0.043020,12.599248,0.874653,0.477681,0.058925
min,0.025732,0.037708,0.389186,-1.257000,69.165700,25.414900,0.625897,29.005000,0.000000,0.000000
25%,0.026702,0.039512,0.752966,0.054711,70.855900,25.468900,224.989000,31.000000,0.000000,0.000000
50%,0.026950,0.040114,1.004280,0.054711,71.108800,25.487900,230.856000,32.000000,0.000000,0.000000
75%,0.027231,0.040680,1.206840,0.054711,71.290200,25.515800,237.001000,32.000000,1.000000,0.000000
max,0.028020,0.042322,206.652000,0.710565,72.044700,25.688600,254.249000,32.996600,1.000000,1.000000

.\valve1\4.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000
mean,0.027110,0.040433,1.201713,0.074476,70.478726,25.340489,229.891518,31.905063,0.318721,0.003653
std,0.000341,0.000865,6.980430,0.248064,0.886093,0.051068,13.068877,0.548032,0.466194,0.060357
min,0.025975,0.038143,0.384079,-0.929070,67.973700,25.214600,1.209740,31.000000,0.000000,0.000000
25%,0.026876,0.039831,0.773417,0.054711,70.125050,25.290050,223.892000,31.992800,0.000000,0.000000
50%,0.027121,0.040453,1.006020,0.054711,70.604700,25.352100,230.768000,32.000000,0.000000,0.000000
75%,0.027348,0.041036,1.222370,0.382638,70.937650,25.377800,236.757500,32.000000,1.000000,0.000000
max,0.028162,0.042785,231.801000,0.710565,72.174100,25.431900,254.614000,33.000000,1.000000,1.000000

.\valve1\5.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000,1154.00000,1154.000000
mean,0.027259,0.040369,1.167129,0.084548,70.940327,25.159637,230.839492,31.398671,0.34922,0.003466
std,0.000419,0.000838,7.101282,0.261901,0.275550,0.053466,12.464528,1.232913,0.47693,0.058798
min,0.026126,0.038189,0.374356,-0.929070,69.908000,25.056600,1.369790,29.000000,0.00000,0.000000
25%,0.026951,0.039796,0.735958,0.054711,70.828550,25.111125,225.222250,30.000000,0.00000,0.000000
50%,0.027256,0.040377,0.932811,0.054711,70.974250,25.162500,230.915500,32.000000,0.00000,0.000000
75%,0.027564,0.040956,1.194965,0.382638,71.153725,25.199775,236.238500,32.000000,1.00000,0.000000
max,0.028381,0.042491,242.018000,1.038490,71.447300,25.275400,254.568000,33.000000,1.00000,1.000000

.\valve1\6.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000,1154.000000
mean,0.027469,0.040493,1.171056,0.064941,69.874411,25.013223,230.564553,31.997424,0.350953,0.003466
std,0.000416,0.001115,6.778300,0.257852,0.825751,0.051064,12.647964,0.702813,0.477475,0.058798
min,0.025911,0.037424,0.360870,-0.929070,68.188900,24.906800,1.236710,30.011700,0.000000,0.000000
25%,0.027160,0.039708,0.729828,0.054711,69.347950,24.965725,224.917500,31.988200,0.000000,0.000000
50%,0.027481,0.040439,0.991071,0.054711,69.676750,25.010000,230.847000,32.000000,0.000000,0.000000
75%,0.027771,0.041142,1.210003,0.054711,70.062125,25.062300,237.157750,32.012600,1.000000,0.000000
max,0.028540,0.044457,231.046000,1.366420,71.821500,25.136300,254.621000,33.000000,1.000000,1.000000

.\valve1\7.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1094.000000,1094.000000,1094.000000,1094.000000,1094.000000,1094.000000,1094.000000,1094.000000,1094.000000,1094.000000
mean,0.027602,0.040367,1.384951,0.066102,70.258711,24.911883,230.325904,31.446240,0.370201,0.003656
std,0.000413,0.000956,9.940935,0.271766,0.185732,0.033543,14.639219,1.580835,0.483079,0.060384
min,0.026426,0.037818,0.394177,-0.929070,69.735000,24.847700,0.996576,28.000000,0.000000,0.000000
25%,0.027306,0.039716,0.717912,0.054711,70.116825,24.888450,225.033750,29.972600,0.000000,0.000000
50%,0.027617,0.040375,0.970570,0.054711,70.261900,24.906100,230.783500,32.012900,0.000000,0.000000
75%,0.027928,0.041072,1.196085,0.300656,70.394850,24.929275,237.195250,32.986500,1.000000,0.000000
max,0.028629,0.043037,234.759000,1.038490,70.802600,24.998000,254.413000,33.000000,1.000000,1.000000

.\valve1\8.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000
mean,0.027604,0.041142,1.183785,0.073057,69.551782,24.846838,230.671944,31.480010,0.349650,0.003497
std,0.000436,0.001145,6.939522,0.261425,0.371920,0.015667,12.789339,0.876129,0.477068,0.059054
min,0.026384,0.038173,0.355411,-0.601143,68.797100,24.813000,1.100050,29.033300,0.000000,0.000000
25%,0.027285,0.040347,0.764157,0.054711,69.225975,24.834000,224.598500,30.983700,0.000000,0.000000
50%,0.027619,0.041129,0.991051,0.054711,69.597700,24.846850,230.882500,32.000000,0.000000,0.000000
75%,0.027920,0.041885,1.198972,0.382638,69.853425,24.856225,236.948500,32.000000,1.000000,0.000000
max,0.028730,0.044458,235.522000,1.038490,70.322400,24.900600,254.507000,33.000000,1.000000,1.000000

.\valve1\9.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000,1148.000000
mean,0.027637,0.041106,1.563853,0.051854,69.292892,24.789874,229.904255,30.748292,0.350174,0.003484
std,0.000470,0.001319,11.435443,0.263382,0.646443,0.026985,16.235582,2.154293,0.477232,0.058951
min,0.025958,0.037496,0.385897,-0.929070,67.117900,24.722600,1.222410,26.038500,0.000000,0.000000
25%,0.027277,0.040163,0.725281,0.054711,68.935625,24.774200,224.140500,27.981800,0.000000,0.000000
50%,0.027667,0.041104,0.993634,0.054711,69.255050,24.789700,230.949000,32.000000,0.000000,0.000000
75%,0.028000,0.042017,1.210815,0.054711,69.814725,24.805600,236.844000,32.000000,1.000000,0.000000
max,0.028844,0.045301,229.175000,1.694350,70.382000,24.858300,254.576000,33.000000,1.000000,1.000000

.\valve2\0.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000,1125.000000
mean,0.027595,0.039414,1.578356,0.038971,68.759219,24.329524,230.316765,32.038678,0.350222,0.003556
std,0.000365,0.001030,11.757032,0.260521,1.442933,0.030782,16.051073,0.584108,0.477252,0.059549
min,0.026713,0.036556,0.388312,-0.929070,65.089000,24.263500,0.755252,31.000000,0.000000,0.000000
25%,0.027337,0.038737,0.747805,0.054711,67.600900,24.302500,224.445000,31.963700,0.000000,0.000000
50%,0.027589,0.039446,0.984952,0.054711,69.408400,24.334700,230.925000,32.000000,0.000000,0.000000
75%,0.027831,0.040175,1.210770,0.054711,69.801200,24.353100,237.140000,32.037400,1.000000,0.000000
max,0.030677,0.042154,243.829000,0.710565,70.474800,24.402800,255.169000,33.000000,1.000000,1.000000

.\valve2\1.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1063.000000,1063.000000,1063.000000,1063.000000,1063.000000,1063.000000,1063.000000,1063.000000,1063.000000,1063.000000
mean,0.027663,0.040037,1.195240,0.048541,67.895174,24.265096,229.924824,31.472275,0.313264,0.003763
std,0.000333,0.001086,7.113407,0.270689,0.695198,0.021573,13.259556,1.314535,0.464039,0.061256
min,0.026455,0.036972,0.394058,-0.929070,66.201900,24.217000,0.580776,28.040000,0.000000,0.000000
25%,0.027434,0.039276,0.753505,0.054711,67.412450,24.252950,223.570000,31.039050,0.000000,0.000000
50%,0.027674,0.040098,1.002720,0.054711,67.955000,24.267200,230.634000,32.000000,0.000000,0.000000
75%,0.027892,0.040828,1.194580,0.054711,68.515500,24.277450,236.960000,32.038900,1.000000,0.000000
max,0.028554,0.043122,232.734000,1.038490,69.098200,24.332300,254.125000,33.000000,1.000000,1.000000

.\valve2\2.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,1129.000000,1129.000000,1129.000000,1129.000000,1129.000000,1129.000000,1129.000000,1129.000000,1129.000000,1129.000000
mean,0.027610,0.040199,0.984195,0.071848,68.038492,24.200085,230.906186,31.585149,0.349867,0.003543
std,0.000369,0.001238,0.268601,0.270217,0.834562,0.024996,10.475457,0.771671,0.477139,0.059444
min,0.026528,0.036425,0.383591,-0.601143,65.705000,24.147100,204.164000,30.000000,0.000000,0.000000
25%,0.027365,0.039321,0.767588,0.054711,67.408400,24.178400,225.513000,31.000000,0.000000,0.000000
50%,0.027606,0.040245,1.001410,0.054711,68.264000,24.199300,231.132000,32.000000,0.000000,0.000000
75%,0.027847,0.041092,1.212050,0.382638,68.721700,24.220800,236.728000,32.000000,1.000000,0.000000
max,0.031339,0.043516,1.525770,1.038490,69.333900,24.255400,254.734000,32.960300,1.000000,1.000000

.\valve2\3.csv

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS,anomaly,changepoint
count,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000
mean,0.027484,0.039381,0.946316,0.061302,68.422053,24.144166,230.839043,31.055089,0.396985,0.004020
std,0.000329,0.001269,0.270188,0.253414,0.909200,0.023696,10.595899,1.601005,0.489519,0.063309
min,0.026671,0.036098,0.386527,-0.929070,66.107800,24.096200,203.891000,28.000000,0.000000,0.000000
25%,0.027257,0.038474,0.714065,0.054711,67.776350,24.122850,225.202500,29.000000,0.000000,0.000000
50%,0.027486,0.039386,0.945265,0.054711,68.676700,24.146400,231.070000,32.000000,0.000000,0.000000
75%,0.027713,0.040323,1.176545,0.054711,69.204750,24.162300,237.031500,32.000000,1.000000,0.000000
max,0.028377,0.042918,1.536930,0.710565,69.832200,24.204700,253.830000,32.958100,1.000000,1.000000